//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StopWatch
{
    using System;
    using System.Collections.Generic;
    
    public partial class Query
    {
        public System.Guid GUID { get; set; }
        public System.Guid URLGUID { get; set; }
        public string QueryString { get; set; }
        public System.DateTime CreatedDTS { get; set; }
        public string CreatedUser { get; set; }
    
        public virtual URL URL { get; set; }
    }
}
