//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StopWatch
{
    using System;
    using System.Collections.Generic;
    
    public partial class URL
    {
        public URL()
        {
            this.Queries = new HashSet<Query>();
        }
    
        public System.Guid GUID { get; set; }
        public System.Guid AnalyticsID { get; set; }
        public string URLString { get; set; }
        public System.DateTime CreatedDTS { get; set; }
        public string CreatedUser { get; set; }
    
        public virtual ICollection<Query> Queries { get; set; }
        public virtual UserAnalytic UserAnalytic { get; set; }
    }
}
