//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StopWatch
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAnalytic
    {
        public UserAnalytic()
        {
            this.URLs = new HashSet<URL>();
        }
    
        public System.Guid GUID { get; set; }
        public System.Guid UserGUID { get; set; }
        public string Method { get; set; }
        public string Area { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public int ClickCount { get; set; }
        public bool Favorites { get; set; }
        public Nullable<System.DateTime> LastAccessedDTS { get; set; }
        public System.DateTime CreatedDTS { get; set; }
        public string CreatedUser { get; set; }
    
        public virtual ICollection<URL> URLs { get; set; }
    }
}
